// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLeBZuSm58vPy6R-fQ4hFW4u8BPADOutY',
    appId: '1:194624997967:web:ab3c06f0c576daa475383a',
    messagingSenderId: '194624997967',
    projectId: 'projectplanner-a',
    authDomain: 'projectplanner-a.firebaseapp.com',
    storageBucket: 'projectplanner-a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHcJIIyMROII0ISYx9vZUWcUsgjY1OX-k',
    appId: '1:194624997967:android:2978ba2fc99920cf75383a',
    messagingSenderId: '194624997967',
    projectId: 'projectplanner-a',
    storageBucket: 'projectplanner-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAST1tHOesR4vFnNjAzMrdxO4cCu3Hene4',
    appId: '1:194624997967:ios:fcacafd90138398775383a',
    messagingSenderId: '194624997967',
    projectId: 'projectplanner-a',
    storageBucket: 'projectplanner-a.appspot.com',
    iosClientId: '194624997967-cgn3p7mo5i07has0nfqlo2k7uhknfdtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAST1tHOesR4vFnNjAzMrdxO4cCu3Hene4',
    appId: '1:194624997967:ios:fcacafd90138398775383a',
    messagingSenderId: '194624997967',
    projectId: 'projectplanner-a',
    storageBucket: 'projectplanner-a.appspot.com',
    iosClientId: '194624997967-cgn3p7mo5i07has0nfqlo2k7uhknfdtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
